all: gestor cliente verificador

gestor: gestor.c
	gcc  gestor.c -o ges

cliente: cliente.c
	gcc cliente.c -o cliente

verificador:
	gcc  Verificador.c -o Verificador

clean:
	rm ges
	rm Verificador
	rm cliente
